language: generic

services:
  - docker

env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json

deploy:
  - provider: script
    script: 
      - chmod +x my-script.sh
      - ./deploy.sh
    skip_cleanup: true
    on:
      branch: master
